app:
  image-download-base-url: ${IMAGE_DOWNLOAD_BASE_URL}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true