jwt:
  keys:
    public: file:${JWT_KEY_FOLDER}/app.pub
    private: file:${JWT_KEY_FOLDER}/app.key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
