name: image_processor

services:
  image-processor-engine:
    build: services/engine
    ports:
      - "8081:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - envs/database.env
      - envs/rabbitmq.env

  image-processor-notification:
    build: services/notification
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - envs/database.env
      - envs/rabbitmq.env
      - envs/mail.env

  image-processor-rest-api:
    build: services/rest-api
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - envs/database.env
      - envs/rabbitmq.env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - envs/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./confs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 5